repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [--config=config/ruff.toml, --fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--config-file=config/mypy.ini]
        additional_dependencies: [types-requests, types-python-dateutil]

  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: pytest -c config/pytest.ini
        language: system
        pass_filenames: false
        always_run: true
