src = ["src", "tests"]
target-version = "py310"
line-length = 79
fix = true

[lint]
select = ["ALL"]
ignore = [
    "D",  # pydocstyle
    "S101",  # assert
    "PGH003",  # code error
    "E721",  # isinstance
    "PT012",  # pytest.raises
    "ANN101",  # self annotation
]

[format]
docstring-code-format = true
