src = ["src", "tests"]
target-version = "py310"
line-length = 79
fix = true

[lint]
select = ["ALL"]
ignore = [
    "D",  # ignore pydocstyle
    "S101",  # assert ignore
    "PGH003",  # code error ignore
    "E721",  # isinstance ignore,
    "PT012",  # pytest.raises
    "ANN001",  # first parameters of the method ignore (for example: self)
]

[format]
docstring-code-format = true
